### ISSUE TITLE
Allow Users to turn off Verbose logging via configuration

### ISSUE THREAD

**Issue by StephenHynes7** [LogentriesCommunity/le_ios#12]
Currently users must change the library code to turn off Verbose logging.

@jlnbuiles suggests the following
```
The easiest way (IMO) would probably be to allow developers to set the variable outside of the library’s code base (maybe in the <app name>-prefix.h file?). This prevents developers from having to modify your libraries after updates.

This is how CocoaLumberjack (a logging library) accomplishes it.

ex: 
#if DEBUG 
static const int logLevel = LOG_LEVEL_VERBOSE; 
#else 
static const int logLevel = LOG_LEVEL_WARNING; 
#endif

**Comment by aviell** [comment]
I'd prefer it would be just an API "debugEnabled" property or a pre-processor macro which can configured in the Podfile.
This is Flurry's method and many other 3rd party libs: http://flurrydev.github.io/FlurryiOSSDK6xAPI/interface_flurry.html#a68104a89eff2e63d71b413d3212c5178
This is Mixpanel's method: https://mixpanel.com/help/reference/ios#debugging-and-logging

**Comment by joelrfcosta** [comment]
I've created a [pull request] (https://github.com/logentries/le_ios/pull/22) to fix this issue (with Swift support too). Please check it and leave some feedback.
